### PR TITLE
bump to cni 1.2.0 for k8s 1.27

### PR DESCRIPTION
**Pull request by kwmonroe**
LP: https://bugs.launchpad.net/charm-kubernetes-master/+bug/2007425

### CODE REVIEW

**Review by mateoflorido — APPROVED** [review]
LGTM! The only doubt I had was about the use of go1.18. After seeing [this](https://github.com/containernetworking/plugins/blob/main/.github/workflows/test.yaml#L7), I now understand why.

**Comment by Cynerva** [comment]
Hold please. I need to see if https://github.com/containernetworking/plugins/pull/633 affects this.

**Comment by Cynerva** [comment]
Yeah, so, the flannel plugin was removed in [CNI plugins v1.0.1](https://github.com/containernetworking/plugins/releases/tag/v1.0.1). I'm pretty sure the flannel charm assumes that kubernetes-control-plane and kubernetes-worker will provide it. This will break our flannel support unless one of our charms (probably flannel) installs the [new standalone flannel CNI plugin](https://github.com/flannel-io/cni-plugin).

**Review by Cynerva — CHANGES_REQUESTED** [review]
See above comment about flannel plugin.

**Comment by kwmonroe** [comment]
Closing for now; will revisit with a flannel plan post-1.27.

**Pull request closed without merging**
